export const ADD_USER_START = 'ADD_USER_START'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_ERROR = 'ADD_USER_ERROR'
export const ADD_USER_HIDE_ALERT = 'ADD_USER_HIDE_ALERT'
