export const ADD_USER_START = 'ADD_USER_START'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_ERROR = 'ADD_USER_ERROR'
export const ADD_USER_HIDE_ALERT = 'ADD_USER_HIDE_ALERT'

export const SELECT_USER_START = 'SELECT_USER_START'
export const SELECT_USER_SUCCESS = 'SELECT_USER_SUCCESS'

export const DELETE_USER_START = 'DELETE_USER_START'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'

export const GET_USER_START = 'GET_USER_START'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const EDIT_USER_START = 'EDIT_USER_START'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR'
export const EDIT_USER_HIDE_ALERT = 'EDIT_USER_HIDE_ALERT'
